# -*- coding: utf-8 -*-
"""Boolean Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRe41ynsaqHUVd1_aRA62suRMbMSoJE4

# Boolean Classification
"""

import pandas as pd

from pandas import DataFrame

df_dataset = pd.read_excel("diabetes.xlsx")

df_dataset

y = df_dataset["Outcome"]
X = df_dataset.drop(["Outcome"], axis = 1)

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=26)

X_train

y_train

X_test

y_test

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier().fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)