# -*- coding: utf-8 -*-
"""Multilabel Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YyTqvFXVamwFLj3_56Ns-Mf69Qd8BYh

# Multilabel Classification
"""

import pandas as pd
from pandas import DataFrame
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df_dataset = pd.read_excel("Iris.xlsx")

df_dataset

y = df_dataset["Species"]
X = df_dataset.drop(["Species"], axis = 1)

X

y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=35)

len(X_train)

len(y_train)

len(X_test)

len(y_test)

rf_model = RandomForestClassifier().fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

y_pred

accuracy_score(y_test, y_pred)